import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "../components/Navbar";
import AuthProvider from "@/components/AuthProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "InSocial",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
